INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (1, 'Move ', 1, '00:04:55');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (2, 'Rock and Roll', 1, '00:03:41');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (3, 'The Battle of Evermore', 1, '00:05:52');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (4, 'Stairway to Heaven', 1, '00:08:03');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (5, 'Misty Mountain Hop', 1, '00:04:39');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (6, 'Four Sticks', 1, '00:04:45');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (7, 'Going to California', 1, '00:03:32');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (8, 'When the Levee Breaks', 1, '00:07:09');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (9, 'Immigrant Song', 2, '00:02:26');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (12, 'Friends', 2, '00:03:54');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (13, 'Celebration Day', 2, '00:03:30');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (14, 'Since I''ve Been Loving You', 2, '00:07:24');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (15, 'Out on the Tiles', 2, '00:04:07');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (16, 'Gallows Pole', 2, '00:04:58');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (17, 'Tangerine', 2, '00:03:12');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (18, 'That''s the Way', 2, '00:05:37');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (19, 'Bron-Y-Aur Stomp', 2, '00:04:17');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (20, 'Hats off To (Roy) Harper', 2, '00:03:42');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (45, 'Papercut', 9, '00:03:04');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (46, 'One Step Closer', 9, '00:02:35');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (47, 'With You', 9, '00:03:23');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (48, 'Points of Authority', 9, '00:03:20');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (49, 'Crawling', 9, '00:03:29');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (50, 'Runaway', 9, '00:03:03');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (51, 'By Myself', 9, '00:03:09');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (52, 'In the End', 9, '00:03:36');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (53, 'A Place for My Head', 9, '00:03:04');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (54, 'Forgotten', 9, '00:03:14');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (55, 'Cure for the Itch', 9, '00:02:37');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (56, 'Pushing Me Away', 9, '00:03:11');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (57, 'Devour', 10, '00:03:50');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (58, 'The Sound of Madness', 10, '00:03:54');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (59, 'Second Chance', 10, '00:03:40');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (60, 'Cry for Help', 10, '00:03:20');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (61, 'The Crow And the Butterfly', 10, '00:04:13');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (62, 'If You Only Knew', 10, '00:03:46');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (63, 'Sin with a Grin', 10, '00:04:00');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (64, 'What a Shame', 10, '00:04:18');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (65, 'Cyanide Sweet Tooth Suicide', 10, '00:03:11');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (66, 'Breaking Inside ', 10, '00:03:51');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (67, 'Call Me', 10, '00:03:43');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (79, 'Going Under', 12, '00:03:35');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (80, 'Bring Me to Life ', 12, '00:03:56');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (81, 'Everybody''s Fool', 12, '00:03:16');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (82, 'Taking Over Me', 12, '00:03:49');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (83, 'Hello', 12, '00:03:40');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (84, 'My Immortal', 12, '00:04:23');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (85, 'My Last Breath', 12, '00:04:07');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (86, 'Haunted', 12, '00:03:05');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (87, 'Whisper', 12, '00:05:27');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (88, 'Tourniquet', 12, '00:04:38');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (89, 'My Immortal (band version)', 12, '00:04:33');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (90, 'Imaginary', 12, '00:04:16');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (91, 'Girls on the Dance Floor', 14, '00:03:54');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (92, 'Like a G6', 14, '00:03:36');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (93, 'Rocketeer', 14, '00:03:31');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (94, 'If I Was You (OMG)', 14, '00:03:25');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (95, 'She Owns the Night', 14, '00:04:02');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (96, 'So What?', 14, '00:03:24');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (97, 'Don''t Look Now', 14, '00:03:33');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (98, 'Fighting for Air', 14, '00:03:45');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (99, 'White Flag', 14, '00:03:48');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (100, '2gether', 14, '00:03:05');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (101, 'Attack', 15, '00:03:09');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (102, 'A Beautiful Lie', 15, '00:04:05');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (103, 'The Kill', 15, '00:03:51');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (104, 'Was It a Dream?', 15, '00:04:15');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (105, 'The Fantasy', 15, '00:04:29');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (106, 'Savior', 15, '00:03:11');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (107, 'From Yesterday', 15, '00:04:07');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (108, 'The Story', 15, '00:03:55');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (109, 'R-Evolve', 15, '00:03:59');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (110, 'Battle of One', 15, '00:02:47');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (111, 'A Modern Myth', 15, '00:14:14');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (112, 'Hunter', 15, '00:03:54');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (113, 'Genesis', 17, '00:03:54');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (114, 'Let There Be Light', 17, '00:04:55');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (115, 'D.A.N.C.E.', 17, '00:04:02');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (116, 'Newjack', 17, '00:03:36');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (117, 'Phantom', 17, '00:04:22');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (118, 'Phantom Pt. II', 17, '00:03:20');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (119, 'Valentine', 17, '00:02:56');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (120, 'Tthhee Ppaarrttyy', 17, '00:04:58');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (121, 'DVNO', 17, '00:03:56');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (122, 'Stress', 17, '00:04:58');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (123, 'Waters of Nazareth', 17, '00:04:25');
INSERT INTO wynns_db.Songs (songID, songName, albumID, songLength) VALUES (124, 'One Minute to Midnight', 17, '00:03:41');